In [2]:
#import libraries
import numpy as np
import pandas as pd
import sklearn

from sklearn import preprocessing

from sklearn.feature_extraction.text import CountVectorizer

import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

import statsmodels.api as sm


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [3]:
#import dataset
data= pd.read_csv(r'C:\Users\Robert\Desktop\mbti_1.csv')

In [4]:
data.head()

type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [5]:
#Add a column to specify if extroverted.
data['extroverted']= data.type.str[:1]
#df['New_Sample'] = df.Sample.str[:1]

data.head()

type                                              posts extroverted
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...           I
1  ENTP  'I'm finding the lack of me in these posts ver...           E
2  INTP  'Good one  _____   https://www.youtube.com/wat...           I
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...           I
4  ENTJ  'You're fired.|||That's another silly misconce...           E

In [6]:
#how many is I vs. E in dataset?
data.describe()

type                                              posts extroverted
count   8675                                               8675        8675
unique    16                                               8675           2
top     INFP  'Mmhhhh... Based on pure sadism, I tortured a ...           I
freq    1832                                                  1        6676

In [7]:
#breakdown of types in survery
type_data = data.groupby('type')
type_data.describe()

extroverted                  posts         \
           count unique top  freq count unique   
type                                             
ENFJ         190      1   E   190   190    190   
ENFP         675      1   E   675   675    675   
ENTJ         231      1   E   231   231    231   
ENTP         685      1   E   685   685    685   
ESFJ          42      1   E    42    42     42   
ESFP          48      1   E    48    48     48   
ESTJ          39      1   E    39    39     39   
ESTP          89      1   E    89    89     89   
INFJ        1470      1   I  1470  1470   1470   
INFP        1832      1   I  1832  1832   1832   
INTJ        1091      1   I  1091  1091   1091   
INTP        1304      1   I  1304  1304   1304   
ISFJ         166      1   I   166   166    166   
ISFP         271      1   I   271   271    271   
ISTJ         205      1   I   205   205    205   
ISTP         337      1   I   337   337    337   

                                                              
                                                    top freq  
type                                                          
ENFJ  'I'm currently dating an ISFP and it's the mos...    1  
ENFP  'Is there something specific that you go in ex...    1  
ENTJ  'intj =same functions in similar order.  we ar...    1  
ENTP  'The OP shows a writing example.  According to...    1  
ESFJ  'I was just curious. I dont see many ESFJ on h...    1  
ESFP  'I recently watched all of Unbreakable Kimmy S...    1  
ESTJ  'People have their priorities. It sounds like ...    1  
ESTP  'I WAS ALSO A LONER. Glad it's not just me, I ...    1  
INFJ  'i like it!!  here's a song i used to think de...    1  
INFP  'Turtles mating are really cute though|||Their...    1  
INTJ  'Not all INTJ's are direct. Those disregard so...    1  
INTP  'Well my thoughts on the meaning of that were ...    1  
ISFJ  52/100 masculine 53/100 feminine 55/100 androg...    1  
ISFP  '- They're like people who baked a beautiful c...    1  
ISTJ  'i have the need to feel wanted, but not reall...    1  
ISTP  'I don't deserve my mother|||You know they're ...    1

In [8]:
data['extroverted'].replace(['I','E'],['0','1'],inplace=True)

data.head()

type                                              posts extroverted
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...           0
1  ENTP  'I'm finding the lack of me in these posts ver...           1
2  INTP  'Good one  _____   https://www.youtube.com/wat...           0
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...           0
4  ENTJ  'You're fired.|||That's another silly misconce...           1

In [9]:
data.dtypes

type           object
posts          object
extroverted    object
dtype: object

In [10]:
data['extroverted'] = data['extroverted'].astype('int')

In [11]:
data.dtypes

type           object
posts          object
extroverted     int32
dtype: object

In [12]:
from sklearn.feature_extraction import text 
stop_words = text.ENGLISH_STOP_WORDS.union(['http', 'isfj', 'infp', 'intj', 'https', 'youtube', 'enfp', 'entp',
                                            'infj', 'infp', 'intj','intp',
 'intp','istj', 'istp', '00', 'enfps', 'entps', 'infjs', 'enfjs', 'estps',
                                            'entj', 'esfjs', 'existence', 'infps', 'enfj', 'entjs', 'intps',
 '000',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '100',
 '1000',
 '101',
 '10th',
 '11',
 '110',
 '11th',
 '12',
 '120',
 '13',
 '130',
 '14',
 '140',
 '15',
 '150',
 '16',
 '16personalities',
 '17',
 '18',
 '180',
 '19',
 '1984',
 '1995',
 '1s',
 '1st',
 '1w2',
 '1w9',
 '20',
 '200',
 '2000',
 '2001',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '20s',
 '20th',
 '21',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '2nd',
 '2w1',
 '2w3',
 '30',
 '300',
 '30s',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '3D',
 '3rd',
 '3s',
 '3w2',
 '3w4',
 '40',
 '400',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '4s',
 '4th',
 '4w3',
 '4w5',
 '50',
 '500',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '564x',
 '57',
 '58',
 '59',
 '5s',
 '5th',
 '5w4',
 '5w6',
 '60',
 '600',
 '60s',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '6s',
 '6th',
 '6w5',
 '6w7',
 '70',
 '70s',
 '71',
 '72',
 '73',
 '736x',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '7s',
 '7th',
 '7w6',
 '7w8',
 '80',
 '80s',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '8s',
 '8th',
 '8w7',
 '8w9',
 '90',
 '90s',
 '91',
 '92',
 '94',
 '95',
 '98',
 '99',
 '9s',
 '9th',
 '9w1',
 '9w8', '125',
 '160',
 '2003',
 '2004',])

In [13]:
#create our count vectorizer
count_vectorizer = CountVectorizer(analyzer='word', min_df=1, stop_words = stop_words, lowercase=True,max_features=1000)

#Transform the list of strings
transform = count_vectorizer.fit_transform(data.posts).toarray()

In [14]:
count_vectorizer.get_stop_words()

frozenset({'00',
           '000',
           '01',
           '02',
           '03',
           '04',
           '05',
           '06',
           '07',
           '08',
           '09',
           '10',
           '100',
           '1000',
           '101',
           '10th',
           '11',
           '110',
           '11th',
           '12',
           '120',
           '125',
           '13',
           '130',
           '14',
           '140',
           '15',
           '150',
           '16',
           '160',
           '16personalities',
           '17',
           '18',
           '180',
           '19',
           '1984',
           '1995',
           '1s',
           '1st',
           '1w2',
           '1w9',
           '20',
           '200',
           '2000',
           '2001',
           '2003',
           '2004',
           '2005',
           '2006',
           '2007',
           '2008',
           '2009',
           '2010',
           '2011',
           '2012',
   

In [15]:
transform

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [2, 1, 2, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 1],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 0]], dtype=int64)

In [16]:
transform.shape

(8675, 1000)

In [17]:
count_vectorizer.get_feature_names()

['ability',
 'able',
 'absolutely',
 'accept',
 'according',
 'accurate',
 'act',
 'action',
 'actions',
 'actual',
 'actually',
 'add',
 'admit',
 'advice',
 'afraid',
 'age',
 'ago',
 'agree',
 'ah',
 'albums',
 'alot',
 'alright',
 'amazing',
 'anger',
 'angry',
 'animals',
 'anime',
 'annoying',
 'answer',
 'answers',
 'anxiety',
 'anymore',
 'anyways',
 'apparently',
 'appreciate',
 'approach',
 'area',
 'aren',
 'argument',
 'art',
 'article',
 'ask',
 'asked',
 'asking',
 'ass',
 'assume',
 'attention',
 'attracted',
 'attractive',
 'avatar',
 'average',
 'avoid',
 'aware',
 'away',
 'awesome',
 'awkward',
 'baby',
 'bad',
 'based',
 'basically',
 'beautiful',
 'bed',
 'beginning',
 'behavior',
 'believe',
 'best',
 'better',
 'big',
 'biggest',
 'bit',
 'black',
 'blue',
 'blushed',
 'body',
 'book',
 'books',
 'bored',
 'boring',
 'born',
 'bother',
 'boy',
 'boyfriend',
 'brain',
 'break',
 'bring',
 'brother',
 'btw',
 'bunch',
 'business',
 'busy',
 'buy',
 'called',
 'calm

In [18]:
#deploy and evaluate model
X=transform
y= data.extroverted
LogReg = LogisticRegression()
log_model = LogReg.fit(X, y)
print(LogReg.score(X, y))

0.830662824207


In [19]:
y_pred = LogReg.predict(X)
from sklearn.metrics import classification_report
#print(classification_report(y, y_pred))
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [20]:
#predict probability
LogReg.predict_proba(X)

array([[ 0.98180255,  0.01819745],
       [ 0.22500971,  0.77499029],
       [ 0.98674598,  0.01325402],
       ..., 
       [ 0.80130952,  0.19869048],
       [ 0.59378276,  0.40621724],
       [ 0.9173912 ,  0.0826088 ]])

In [21]:
# Check trained model intercept
print("Intercept is ",  log_model.intercept_)

# Check trained model coefficients
print("Coefficients are",  log_model.coef_)

Intercept is  [-0.89060477]
Coefficients are [[ -5.18795795e-02   2.91171474e-02   3.30379450e-02  -2.52217338e-02
    1.37412065e-02  -1.39304847e-01   2.08117823e-02  -1.73868447e-02
    2.31787625e-01   4.49362574e-02  -5.63251853e-04  -4.27907626e-03
    5.84025701e-02   1.96477362e-02  -2.01974397e-01  -1.01396982e-02
    1.05811734e-01  -9.89078115e-03  -4.80763001e-02   1.54051865e-02
    9.92219445e-02  -6.67004645e-02   9.08945652e-02  -4.69050383e-02
    2.81499987e-02  -1.29388299e-01  -3.00523142e-01   1.21355149e-01
    2.38101559e-02  -1.94083253e-01  -5.11974613e-02   1.87907433e-02
   -5.91577012e-02  -4.47164595e-02   1.09363986e-02   7.54703439e-02
    1.07273686e-01  -2.19045335e-02   9.33643444e-02  -4.01389110e-02
   -3.97983295e-02   1.38369639e-02  -3.14090378e-03  -1.57304653e-01
    6.64731772e-02   1.08008774e-02   1.57661526e-01  -5.04208314e-02
   -9.34318547e-02  -1.43143194e-02  -2.16915371e-01   4.71730420e-02
    7.67080794e-02  -4.92726683e-02   1.19734

In [22]:
from sklearn.feature_selection import RFE

rfe = RFE(LogReg, 75)
rfe = rfe.fit(X, y)
print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False False  True False False False
 False False  True False False False False False False False False False
 False  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False  True False False False  True False False False False False
 False False False False False False False False False False False False
 False False False False  True False False False  True False False False
 False False False False  True False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False False False False False  True Fa

In [23]:
rfe.transform(X)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 2, 0, 0]], dtype=int64)

In [24]:
#rfe.score(X, y)

In [25]:
#support = rfe.support_
#Now support is an array, you can use that to efficiently extract the name of your selected features (columns). Make sure your feature names are in a numpy array, not a python list.

#feature_names = np.array(count_vectorizer.get_feature_names()) # transformed list to array

#feature_names[support]

In [26]:
#print ('coefficients',rfe.estimator_.coef_)

In [27]:
#df = pd.DataFrame({'words': feature_names[support], 'coefficients': rfe.estimator_.coef_})
#df

#rfe.estimator_.coef_.shape
#feature_names[support].shape

In [28]:
#broken
#cols = X[support]
#X=X[cols]
#y=y

In [29]:
logit_model=sm.Logit(y,rfe.transform(X))
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.481277
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:            extroverted   No. Observations:                 8675
Model:                          Logit   Df Residuals:                     8600
Method:                           MLE   Df Model:                           74
Date:                Sat, 28 Apr 2018   Pseudo R-squ.:                  0.1084
Time:                        22:16:25   Log-Likelihood:                -4175.1
converged:                       True   LL-Null:                       -4682.7
                                        LLR p-value:                2.422e-165
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0693      0.076      0.906      0.365      -0.081       0.219
x2            -0.2991      0.