In [1]:
#import libraries
import numpy as np
import pandas as pd
import sklearn

from sklearn import preprocessing

from sklearn.feature_extraction.text import CountVectorizer

import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

import statsmodels.api as sm


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:
#import dataset
data= pd.read_csv(r'C:\Users\Robert\Desktop\mbti_1.csv')

In [3]:
data.head()

type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [4]:
#Add a column to specify if extroverted.
data['extroverted']= data.type.str[:1]
#df['New_Sample'] = df.Sample.str[:1]

data.head()

type                                              posts extroverted
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...           I
1  ENTP  'I'm finding the lack of me in these posts ver...           E
2  INTP  'Good one  _____   https://www.youtube.com/wat...           I
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...           I
4  ENTJ  'You're fired.|||That's another silly misconce...           E

In [5]:
#how many is I vs. E in dataset?
data.describe()

type                                              posts extroverted
count   8675                                               8675        8675
unique    16                                               8675           2
top     INFP  'I'm thinking that you are probably INTP. A lo...           I
freq    1832                                                  1        6676

In [6]:
#breakdown of types in survery
type_data = data.groupby('type')
type_data.describe()

extroverted                  posts         \
           count unique top  freq count unique   
type                                             
ENFJ         190      1   E   190   190    190   
ENFP         675      1   E   675   675    675   
ENTJ         231      1   E   231   231    231   
ENTP         685      1   E   685   685    685   
ESFJ          42      1   E    42    42     42   
ESFP          48      1   E    48    48     48   
ESTJ          39      1   E    39    39     39   
ESTP          89      1   E    89    89     89   
INFJ        1470      1   I  1470  1470   1470   
INFP        1832      1   I  1832  1832   1832   
INTJ        1091      1   I  1091  1091   1091   
INTP        1304      1   I  1304  1304   1304   
ISFJ         166      1   I   166   166    166   
ISFP         271      1   I   271   271    271   
ISTJ         205      1   I   205   205    205   
ISTP         337      1   I   337   337    337   

                                                              
                                                    top freq  
type                                                          
ENFJ  'YES! I absolutely love this one, I've stumble...    1  
ENFP  'Also, feel free to ask your teacher if she li...    1  
ENTJ  'Laura Roslin from Battlestar Galactica is a c...    1  
ENTP  'Sort of. Ended up with programming and writin...    1  
ESFJ  '54586  Adelaide Labille-Guiard is my favorite...    1  
ESFP  'You're right. It was wrong of me to assume, b...    1  
ESTJ  'Hey Queen, welcome back!|||Yes to this!! My I...    1  
ESTP  'I WAS ALSO A LONER. Glad it's not just me, I ...    1  
INFJ  'What are these kids thinking, giving me their...    1  
INFP  'Accurate!|||It's interesting how much appeara...    1  
INTJ  'Gah. I copy and pasted but it ended up being ...    1  
INTP  'I'm thinking that you are probably INTP. A lo...    1  
ISFJ  'It has been my experience that istp like inte...    1  
ISFP  'More than anything else, I'm scared to death ...    1  
ISTJ  'The Brothers Karamazov and Notes from the Und...    1  
ISTP  'What is your opinion on them? Their side effe...    1

In [7]:
data['extroverted'].replace(['I','E'],['0','1'],inplace=True)

data.head()

type                                              posts extroverted
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...           0
1  ENTP  'I'm finding the lack of me in these posts ver...           1
2  INTP  'Good one  _____   https://www.youtube.com/wat...           0
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...           0
4  ENTJ  'You're fired.|||That's another silly misconce...           1

In [8]:
data.dtypes

type           object
posts          object
extroverted    object
dtype: object

In [9]:
data['extroverted'] = data['extroverted'].astype('int')

In [10]:
data.dtypes

type           object
posts          object
extroverted     int32
dtype: object

In [11]:
from sklearn.feature_extraction import text 
stop_words = text.ENGLISH_STOP_WORDS.union(['http', 'isfj', 'infp', 'intj', 'https', 'youtube', 'enfp', 'entp',
                                            'infj', 'infp', 'intj','intp',
 'intp','istj', 'istp', '00', 'enfps', 'entps', 'infjs', 'enfjs', 'estps',
                                            'entj', 'esfjs', 'existence', 'infps', 'enfj', 'entjs', 'intps',
 '000',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '100',
 '1000',
 '101',
 '10th',
 '11',
 '110',
 '11th',
 '12',
 '120',
 '13',
 '130',
 '14',
 '140',
 '15',
 '150',
 '16',
 '16personalities',
 '17',
 '18',
 '180',
 '19',
 '1984',
 '1995',
 '1s',
 '1st',
 '1w2',
 '1w9',
 '20',
 '200',
 '2000',
 '2001',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '20s',
 '20th',
 '21',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '2nd',
 '2w1',
 '2w3',
 '30',
 '300',
 '30s',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '3D',
 '3rd',
 '3s',
 '3w2',
 '3w4',
 '40',
 '400',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '4s',
 '4th',
 '4w3',
 '4w5',
 '50',
 '500',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '564x',
 '57',
 '58',
 '59',
 '5s',
 '5th',
 '5w4',
 '5w6',
 '60',
 '600',
 '60s',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '6s',
 '6th',
 '6w5',
 '6w7',
 '70',
 '70s',
 '71',
 '72',
 '73',
 '736x',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '7s',
 '7th',
 '7w6',
 '7w8',
 '80',
 '80s',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '8s',
 '8th',
 '8w7',
 '8w9',
 '90',
 '90s',
 '91',
 '92',
 '94',
 '95',
 '98',
 '99',
 '9s',
 '9th',
 '9w1',
 '9w8', '125',
 '160',
 '2003',
 '2004',])

In [46]:
#create our count vectorizer
count_vectorizer = CountVectorizer(analyzer='word', min_df=1, stop_words = stop_words, lowercase=True,max_features=2500)

#Transform the list of strings
transform = count_vectorizer.fit_transform(data.posts).toarray()

In [47]:
count_vectorizer.get_stop_words()

frozenset({'00',
           '000',
           '01',
           '02',
           '03',
           '04',
           '05',
           '06',
           '07',
           '08',
           '09',
           '10',
           '100',
           '1000',
           '101',
           '10th',
           '11',
           '110',
           '11th',
           '12',
           '120',
           '125',
           '13',
           '130',
           '14',
           '140',
           '15',
           '150',
           '16',
           '160',
           '16personalities',
           '17',
           '18',
           '180',
           '19',
           '1984',
           '1995',
           '1s',
           '1st',
           '1w2',
           '1w9',
           '20',
           '200',
           '2000',
           '2001',
           '2003',
           '2004',
           '2005',
           '2006',
           '2007',
           '2008',
           '2009',
           '2010',
           '2011',
           '2012',
   

In [48]:
transform

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [2, 1, 0, ..., 1, 0, 0],
       ..., 
       [0, 0, 0, ..., 1, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
transform.shape

(8675, 2500)

In [50]:
count_vectorizer.get_feature_names()

['ability',
 'able',
 'absolute',
 'absolutely',
 'abstract',
 'abuse',
 'accept',
 'accepted',
 'accepting',
 'accidentally',
 'according',
 'account',
 'accurate',
 'achieve',
 'acquaintances',
 'act',
 'acting',
 'action',
 'actions',
 'active',
 'actively',
 'activities',
 'activity',
 'acts',
 'actual',
 'actually',
 'add',
 'added',
 'addicted',
 'address',
 'adhd',
 'admire',
 'admit',
 'adorable',
 'adore',
 'adult',
 'advantage',
 'adventure',
 'advice',
 'affect',
 'affection',
 'afraid',
 'age',
 'ages',
 'aggressive',
 'agnostic',
 'ago',
 'agree',
 'agreed',
 'ah',
 'ahead',
 'ahh',
 'ain',
 'air',
 'ak',
 'album',
 'albums',
 'alcohol',
 'alive',
 'allow',
 'allowed',
 'allows',
 'alot',
 'alright',
 'alternative',
 'amazing',
 'america',
 'american',
 'amp',
 'amusing',
 'analysis',
 'analyze',
 'analyzing',
 'anger',
 'angry',
 'animal',
 'animals',
 'anime',
 'annoy',
 'annoyed',
 'annoying',
 'annoys',
 'answer',
 'answered',
 'answering',
 'answers',
 'anti',
 'anxie

In [51]:
#deploy and evaluate model
X=transform
y= data.extroverted
LogReg = LogisticRegression()
log_model = LogReg.fit(X, y)
print(LogReg.score(X, y))

0.909740634006


In [52]:
y_pred = LogReg.predict(X)
from sklearn.metrics import classification_report
#print(classification_report(y, y_pred))
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [53]:
#predict probability
LogReg.predict_proba(X)

array([[ 0.98937211,  0.01062789],
       [ 0.34390169,  0.65609831],
       [ 0.99132294,  0.00867706],
       ..., 
       [ 0.98795286,  0.01204714],
       [ 0.89698762,  0.10301238],
       [ 0.98051073,  0.01948927]])

In [54]:
# Check trained model intercept
print("Intercept is ",  log_model.intercept_)

# Check trained model coefficients
print("Coefficients are",  log_model.coef_)

Intercept is  [-0.92184544]
Coefficients are [[-0.03083533  0.01415112 -0.12221829 ..., -0.20225415 -0.24157998
  -0.45216517]]


In [55]:
#from sklearn.feature_selection import RFE

#rfe = RFE(LogReg, 100)
#rfe = rfe.fit(X, y)
#print(rfe.support_)
#print(rfe.ranking_)

In [56]:
#rfe.transform(X)

In [57]:
#rfe.score(X, y)

In [58]:
#support = rfe.support_
#Now support is an array, you can use that to efficiently extract the name of your selected features (columns). Make sure your feature names are in a numpy array, not a python list.

#feature_names = np.array(count_vectorizer.get_feature_names()) # transformed list to array

#feature_names[support]

In [59]:
#print ('coefficients',rfe.estimator_.coef_)

In [60]:
#df = pd.DataFrame({'words': feature_names[support], 'coefficients': rfe.estimator_.coef_})
#df

#rfe.estimator_.coef_.shape
#feature_names[support].shape

In [61]:
#broken
#cols = X[support]
#X=X[cols]
#y=y

In [62]:
logit_model=sm.Logit(y,X)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.222501
         Iterations 10
                           Logit Regression Results                           
Dep. Variable:            extroverted   No. Observations:                 8675
Model:                          Logit   Df Residuals:                     6175
Method:                           MLE   Df Model:                         2499
Date:                Sat, 28 Apr 2018   Pseudo R-squ.:                  0.5878
Time:                        22:59:20   Log-Likelihood:                -1930.2
converged:                       True   LL-Null:                       -4682.7
                                        LLR p-value:                6.053e-227
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0007      0.177      0.004      0.997      -0.346       0.348
x2             0.0230      0