In [44]:
#import libraries
import numpy as np
import pandas as pd
import sklearn

from sklearn import preprocessing

from sklearn.feature_extraction.text import CountVectorizer

import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

import statsmodels.api as sm

In [45]:
#import dataset
data= pd.read_csv(r'mbti_1.csv')

In [46]:
data.head()

type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [47]:
#Add a column to specify if extroverted.
data['extroverted']= data.type.str[:1]
#df['New_Sample'] = df.Sample.str[:1]

data.head()

type                                              posts extroverted
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...           I
1  ENTP  'I'm finding the lack of me in these posts ver...           E
2  INTP  'Good one  _____   https://www.youtube.com/wat...           I
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...           I
4  ENTJ  'You're fired.|||That's another silly misconce...           E

In [ ]:
#how many is I vs. E in dataset?
data.describe()
data['extroverted'].groupby('extroverted').sum()

In [49]:
#breakdown of types in survery
type_data = data.groupby('type')
type_data.describe()

extroverted                  posts         \
           count unique top  freq count unique   
type                                             
ENFJ         190      1   E   190   190    190   
ENFP         675      1   E   675   675    675   
ENTJ         231      1   E   231   231    231   
ENTP         685      1   E   685   685    685   
ESFJ          42      1   E    42    42     42   
ESFP          48      1   E    48    48     48   
ESTJ          39      1   E    39    39     39   
ESTP          89      1   E    89    89     89   
INFJ        1470      1   I  1470  1470   1470   
INFP        1832      1   I  1832  1832   1832   
INTJ        1091      1   I  1091  1091   1091   
INTP        1304      1   I  1304  1304   1304   
ISFJ         166      1   I   166   166    166   
ISFP         271      1   I   271   271    271   
ISTJ         205      1   I   205   205    205   
ISTP         337      1   I   337   337    337   

                                                              
                                                    top freq  
type                                                          
ENFJ  'Sorry, but this is, to put it quite frankly, ...    1  
ENFP  'The movie even gave itself a pass saying it a...    1  
ENTJ  'Can anyone suggest useful nonfiction books in...    1  
ENTP  'I'm an ENTP but I'm going to say that that ha...    1  
ESFJ  'Yep, I'm ESFJ.  Hooray!  http://i40.tinypic.c...    1  
ESFP  '267522|||I've had an office job for almost te...    1  
ESTJ  'I'm a 3w2.  I identify with it completely.|||...    1  
ESTP  '8 months have passed since i last took a visi...    1  
INFJ  'Finally moved and now I live on my own. It fe...    1  
INFP  'Pyroscope, There's a similar thread..'You kno...    1  
INTJ  'Biology is real and it's effects are measurab...    1  
INTP  'I hated gym in school, but I love motor racin...    1  
ISFJ  52/100 masculine 53/100 feminine 55/100 androg...    1  
ISFP  For me, friendships are very casual. I am good...    1  
ISTJ  'First, apologize for adding the the Necro pos...    1  
ISTP  'Fuck me, climbing out of this hole I dug myse...    1

In [50]:
data['extroverted'].replace(['I','E'],['0','1'],inplace=True)

data.head()

type                                              posts extroverted
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...           0
1  ENTP  'I'm finding the lack of me in these posts ver...           1
2  INTP  'Good one  _____   https://www.youtube.com/wat...           0
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...           0
4  ENTJ  'You're fired.|||That's another silly misconce...           1

In [51]:
data.dtypes

type           object
posts          object
extroverted    object
dtype: object

In [52]:
data['extroverted'] = data['extroverted'].astype('int')

In [53]:
data.dtypes

type           object
posts          object
extroverted     int32
dtype: object

In [54]:
from sklearn.feature_extraction import text 
stop_words = text.ENGLISH_STOP_WORDS.union(['http', 'isfj', 'infp', 'intj', 'https', 'com', 'youtube', 'enfp', 'entp',
                                            'infj', 'infp', 'intj','intp',
 'intp','istj', 'istp', '00', 'enfps', 'entps', 'infjs', 'enfjs', 'estps',
                                            'entj', 'esfjs', 'existence', 'infps', 'enfj', 'entjs', 'intps', 'estp', 'ne', 'nt', 'ni', 've',
 '000',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '100',
 '1000',
 '101',
 '10th',
 '11',
 '110',
 '11th',
 '12',
 '120',
 '13',
 '130',
 '14',
 '140',
 '15',
 '150',
 '16',
 '16personalities',
 '17',
 '18',
 '180',
 '19',
 '1984',
 '1995',
 '1s',
 '1st',
 '1w2',
 '1w9',
 '20',
 '200',
 '2000',
 '2001',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '20s',
 '20th',
 '21',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '2nd',
 '2w1',
 '2w3',
 '30',
 '300',
 '30s',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '3D',
 '3rd',
 '3s',
 '3w2',
 '3w4',
 '40',
 '400',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '4s',
 '4th',
 '4w3',
 '4w5',
 '50',
 '500',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '564x',
 '57',
 '58',
 '59',
 '5s',
 '5th',
 '5w4',
 '5w6',
 '60',
 '600',
 '60s',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '6s',
 '6th',
 '6w5',
 '6w7',
 '70',
 '70s',
 '71',
 '72',
 '73',
 '736x',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '7s',
 '7th',
 '7w6',
 '7w8',
 '80',
 '80s',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '8s',
 '8th',
 '8w7',
 '8w9',
 '90',
 '90s',
 '91',
 '92',
 '94',
 '95',
 '98',
 '99',
 '9s',
 '9th',
 '9w1',
 '9w8', '125',
 '160',
 '2003',
 '2004',])

In [55]:
#create our count vectorizer
count_vectorizer = CountVectorizer(analyzer='word', min_df=100, stop_words = stop_words, lowercase=True)

#Transform the list of strings
transform = count_vectorizer.fit_transform(data.posts).toarray()

In [56]:
#shows list of stopwords
#count_vectorizer.get_stop_words()

In [57]:
transform

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [58]:
transform.shape

(8675, 4595)

In [59]:
count_vectorizer.get_feature_names()

['abandoned',
 'abilities',
 'ability',
 'able',
 'absent',
 'absolute',
 'absolutely',
 'absorbed',
 'abstract',
 'absurd',
 'abuse',
 'abused',
 'abusive',
 'academic',
 'accent',
 'accept',
 'acceptable',
 'acceptance',
 'accepted',
 'accepting',
 'access',
 'accident',
 'accidentally',
 'accomplish',
 'accomplished',
 'according',
 'account',
 'accounts',
 'accuracy',
 'accurate',
 'accurately',
 'accused',
 'achieve',
 'acknowledge',
 'acquaintance',
 'acquaintances',
 'act',
 'acted',
 'acting',
 'action',
 'actions',
 'active',
 'actively',
 'activities',
 'activity',
 'actor',
 'actors',
 'acts',
 'actual',
 'actually',
 'ad',
 'adapt',
 'add',
 'added',
 'addicted',
 'addiction',
 'addictive',
 'adding',
 'addition',
 'additional',
 'address',
 'adhd',
 'admire',
 'admit',
 'admitted',
 'admittedly',
 'adopt',
 'adorable',
 'adore',
 'adult',
 'adults',
 'advance',
 'advanced',
 'advantage',
 'adventure',
 'adventures',
 'adventurous',
 'advice',
 'advise',
 'advocate',
 'affe

In [60]:
#deploy and evaluate model
X=transform
y= data.extroverted
LogReg = LogisticRegression()
log_model = LogReg.fit(X, y)
print(LogReg.score(X, y))

0.9996541786743516


In [61]:
y_pred = LogReg.predict(X)
from sklearn.metrics import classification_report
#print(classification_report(y, y_pred))
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [62]:
#predict probability
LogReg.predict_proba(X)

array([[9.99676557e-01, 3.23443127e-04],
       [1.68976183e-01, 8.31023817e-01],
       [9.91869069e-01, 8.13093107e-03],
       ...,
       [9.98742182e-01, 1.25781767e-03],
       [9.46439716e-01, 5.35602838e-02],
       [9.99435418e-01, 5.64581755e-04]])

In [63]:
# Check trained model intercept
print("Intercept is ",  log_model.intercept_)

# Check trained model coefficients
print("Coefficients are",  log_model.coef_)

Intercept is  [-0.99920886]
Coefficients are [[ 0.07640115  0.47803825  0.0073766  ... -0.79152167 -0.33291049
  -0.38872389]]


In [ ]:
#http://scikit-learn.org/stable/auto_examples/feature_selection/plot_rfe_with_cross_validation.html#sphx-glr-auto-examples-feature-selection-plot-rfe-with-cross-validation-py
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.datasets import make_classification

# Create the RFE object and compute a cross-validated score.

# The "accuracy" scoring is proportional to the number of correct
# classifications
rfecv = RFECV(estimator=LogReg, step=1, cv=StratifiedKFold(10),
              scoring='accuracy')
rfecv.fit(X, y)

print("Optimal number of features : %d" % rfecv.n_features_)



In [ ]:
# Plot number of features VS. cross-validation scores
plt.figure()
plt.xlabel("Number of features selected")
plt.ylabel("Cross validation score (nb of correct classifications)")
plt.plot(range(1, len(rfecv.grid_scores_) + 1), rfecv.grid_scores_)
plt.show()

In [ ]:
logit_model=sm.Logit(y,rfecv.transform(X))
result=logit_model.fit()
print(result.summary())

In [ ]:
rfecv.get_support()

In [ ]:
support = rfecv.get_support()
#Now support is an array, you can use that to efficiently extract the name of your selected features (columns). Make sure your feature names are in a numpy array, not a python list.

feature_names = np.array(count_vectorizer.get_feature_names()) # transformed list to array

feature_names_support = feature_names[support]

In [ ]:
rfecv.score(X, y)

In [ ]:
#change max rows to show
pd.options.display.max_rows =100
pd.options.display.max_rows

In [ ]:
final = pd.DataFrame({'feature name':feature_names_support, 'coefficient': result.params})
#https://stackoverflow.com/questions/13148429/how-to-change-the-order-of-dataframe-columns
def order(frame,var):
    if type(var) is str:
        var = [var] #let the command take a string or list
    varlist =[w for w in frame.columns if w not in var]
    frame = frame[var+varlist]
    return frame 
final = order(final, ['feature name'])
final = final.sort_values('coefficient', ascending = False)
final